plugins {
    id 'com.android.application'
}

android {
    namespace 'lab.yugor.teyvatterminal'
    compileSdk 35

    defaultConfig {
        applicationId 'lab.yugor.teyvatterminal'
        minSdk 26
        targetSdk 35

        def runNumber = System.getenv("GITHUB_RUN_NUMBER")
        versionCode runNumber ? 1000 + runNumber.toInteger() : 1000
        versionName '0.4.0'
    }

    signingConfigs {
        release {
            def keystorePath = System.getenv("ANDROID_KEYSTORE_PATH")

            if (keystorePath) {
                storeFile file(keystorePath)
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias System.getenv("ANDROID_KEY_ALIAS")
                keyPassword System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'com.google.mlkit:translate:17.0.3'
}
